### ISSUE TITLE
Feature request : Support for third party repositories

### ISSUE THREAD

**Issue by W1zardK1ng** [GrapheneOS/Apps#287] opened 2023-03-15 11:52 UTC
I am not sure this is something which GOS is interested in doing but it will be nice to have an option to add third party repositories to the Apps, so that users who want to add third party repositories like Newpipe, Molly etc can be added to the apps and can install the app directly from there. This eliminate the use of app store like Droid-ify.

**Comment by r3g-5z** [comment] 2023-03-15 11:56
Duplicate of https://github.com/GrapheneOS/Apps/issues/78

Will not be happening

**Closed by r3g-5z** 2023-03-15 11:56 UTC

**Comment by thestinger** [comment] 2023-03-15 12:00
It goes against the way Android handles app sources to have multiple repositories in a single app. The way F-Droid does it has further issues since it mixes them all together as sources for any app and will switch between them for the same app.
