### ISSUE TITLE
Feature Request - Battery management

### ISSUE THREAD

**Issue by User1966** [GrapheneOS/Apps#308] opened 2023-06-11 13:40 UTC
GIVEN I have copied or licenced ACER battery optimised battery management
or https://chargie.org/blog-list/

WHEN I plug in my device to charge
AND it contains a battery
THEN I can specify that it is not charged above 80% or below 30% to avoid battery degradation from too many discharge cycles?

**Comment by thestinger** [comment] 2023-06-11 15:14
Duplicate of existing issues. Charging is already throttled based on heat and current charge.

Also don't know what you mean by not charged below 30%.

**Closed by thestinger** 2023-06-11 15:14 UTC

**Comment by User1966** [comment] 2023-06-11 16:47
@thestinger This is the planned system of keep charge between 30-80% to avoid battery memory/issues with wear in Lithium batteries

Below 30% starts a full discharge and there are limited number for the life of the battery
One cannot replace the battery in pixel phones, like you can with fairphones or older devices
I think above 80% causes wear on the battery

I can find links if you want more evidence
