### ISSUE TITLE
Remove Google services from app store

### ISSUE THREAD

**Issue by chxsec** [GrapheneOS/Apps#198] opened 2022-08-11 03:51 UTC
Hello, first off I apologize if this is not the right place to ask this, I am unsure how to just ask a question, or if I should actually post an issue for this. I am newer to github and not a developer... 

My question, is there a way to remove the option to install google services, play store and framework etc from "apps" application on GraphenOS? I installed GrapheneOS on my kids phone and would like for them not to have the option at all to install any google services etc. Thank you in advance and again apologies if this is the wrong way to ask this question.

**Comment by thestinger** [comment] 2022-08-11 08:34
Not at the moment.

**Comment by chxsec** [comment] 2022-08-12 04:59
Thank you. Is there anything I can do as a non-developer to help the project out?

**Comment by Zanthed** [comment] 2022-08-12 05:01
This is a dupe of https://github.com/GrapheneOS/Apps/issues/124

**Closed by Zanthed** 2022-08-12 05:01 UTC
