### ISSUE TITLE
Google Play Services download corrupt

### ISSUE THREAD

**Issue by KonigTX** [GrapheneOS/Apps#122] opened 2022-03-03 20:59 UTC
Been trying to get Google Play Services installed but the download reaches ~40% of the 105mb file, the download bar skips to 100% and attempts to install the package. Failure message is: "app is corrupt, cannot be installed." Have tried reinstalling Apps apk, uninstalling Play Store and Google Services Framework to no avail.

**Comment by thestinger** [comment] 2022-03-03 21:03
The error message is correct. You already have an app with a conflicting app id installed. You cannot install another variant of an app with a different signing key or a lower version even in another profile. The signing key is pinned globally and the version needs to be equal or greater. You likely have a newer version of Play services installed already. In the release notes for the release bundling our app repository client, you can see that we blocked the Play Store from updating Play services and the Play Store to prevent users ending up with a newer version than what's in our repository. The issue is primarily due to them taking literally weeks to roll out new versions.

This isn't an issue with GrapheneOS or the app repository client. It's nothing specific to them or to Google Play. It's part of what the package manager on Android enforces for apps in general.

**Comment by thestinger** [comment] 2022-03-03 21:04
Please ask for support in our main Matrix room if you need help resolving this beyond that.

**Closed by thestinger** 2022-03-03 21:03 UTC
